<div class="row">
	<div class="col-md-6 mx-auto">
		<section class="card card-cascade narrower my-3">
		    <div class="row">
		        <div class="col-md-12">
		            <div class="card-header py-3 gradient-card-header btn-elegant">
		            	<h5 class="mb-0">Responder <?= $this->title ?> <small>(Doc: <?= $this->item->getDocumentId(); ?>)</small></h5>
		            </div>
		            <div class="card-body card-body-cascade">
		            <?php
					$form = $this->form;
					$form->prepare();
					$form->setAttribute('action', '/admin/affiliates_claims/answer/' . $this->item->getId());
					$form->setAttribute('method', 'post');
					echo $this->form()->openTag($form);
					?>
		    			<div class="row">
							<div class="col-md-12 mb-4">
								<?= $this->formRow($form->get('claim_id')) ?>

							</div>

							<div class="col-md-12 mb-4">
								<?= $this->formRow($form->get('affiliate_fullname')) ?>

							</div>

							<div class="col-md-12 mb-4">
								<?= $this->formRow($form->get('title')) ?>

							</div>

							<div class="col-md-12 mb-4">
								<?= $this->formRow($form->get('detail')) ?>

							</div>

							<div class="col-md-12 mb-4">
								<?= $this->formRow($form->get('dni')) ?>

							</div>

							<div class="col-md-12 mb-4">
								<?= $this->formRow($form->get('detail_answer')) ?>

							</div>

							<div class="col-md-12">
								<?= $this->formHidden($form->get('date_answer')->setValue('Y-m-d H:i:s')) ?>
								<?= $this->formRow($form->get('submit')) ?>

							</div>
						</div>
						<?= $this->form()->closeTag() ?>

					</div>
		        </div>
		    </div>
		</section>
	</div>
</div>