<?= $this->doctype() ?>

<html lang="es" ng-app="adminApp" data-theme="light" data-layout-mode="fluid" data-topbar-color="light" data-sidenav-size="default" data-sidenav-color="dark" data-layout-position="fixed" class="menuitem-active">

    <head>
        <meta charset="utf-8" />
        <?php 
        echo $this->headTitle('Admin ' . $this->web['config']['name'])->setSeparator(' | ')->setAutoEscape(false);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/favicon.svg', 'id' => 'dark-scheme-icon'])
            ->prependStylesheet('/css/styles.css')
            ->prependStylesheet('/css/app-creative.min.css')
            ->prependStylesheet('/css/icons.min.css');

        ?>

        <script async src="https://www.googletagmanager.com/gtag/js?id=<?= $this->web['config']['analytics'] ?>"></script>
            <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","<?= $this->web['config']['analytics'] ?>");</script>

    </head>

    <body onload="getNotifications()">
        <div class="wrapper">

            <div class="navbar-custom topnav-navbar">
                <div class="container-fluid detached-nav">

                    <button class="button-toggle-menu">
                        <i class="mdi mdi-menu"></i>
                    </button>
                        
                    <button class="navbar-toggle" data-bs-toggle="collapse" data-bs-target="#topnav-menu-content">
                        <div class="lines">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </button>

                    <ul class="list-unstyled topbar-menu float-end mb-0">
                        <li class="dropdown notification-list">
                            <a class="nav-link dropdown-toggle arrow-none" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                <i class="ri-notification-3-line noti-icon"></i>
                                <span class="noti-icon-badge" style="visibility: hidden;"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated dropdown-lg py-0">
                                <div class="p-2 border-top-0 border-start-0 border-end-0 border-dashed border">
                                    <div class="row align-items-center mb-2">
                                        <div class="col">
                                            <h6 class="m-0 font-16 fw-semibold"> Notificaciones</h6>
                                        </div>
                                        <div class="col-auto">
                                            <a href="/admin/dashboard/limpiarNotificaciones" class="text-dark text-decoration-underline clear-btn">
                                                <small>Limpiar todo</small>
                                            </a>
                                        </div>
                                    </div>
                                    <div class="row align-items-center">
                                        <div style="max-height: 230px;" data-simplebar></div>

                                    </div>
                                </div>
                                <a href="/admin/dashboard/notificaciones" class="dropdown-item text-center text-primary notify-item notify-all">Ver todo</a>
                            </div>
                        </li>
                        <li class="dropdown notification-list">
                            <a class="nav-link dropdown-toggle nav-user arrow-none me-0" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
                                <span class="account-user-avatar"> 
                                    <img src="/img/avatar.jpg" alt="user-image" class="rounded-circle">
                                </span>
                                <span>
                                    <span class="account-user-name"><?= $this->identity()['display_name'] ?></span>
                                    <span class="account-position"><?= $this->identity()['rank_name'] ?></span>
                                </span>
                            </a>
                            
                            <div class="dropdown-menu dropdown-menu-end dropdown-menu-animated topbar-dropdown-menu profile-dropdown" style="">
                                <a href="/admin/dashboard/mi-cuenta" class="dropdown-item notify-item">
                                    <i class="mdi mdi-account-circle me-1"></i>
                                    <span>Mi Cuenta</span>
                                </a>
                                <a href="javascript:void(0)" class="dropdown-item notify-item disabled">
                                    <i class="mdi mdi-account-edit me-1"></i>
                                    <span>Ajustes</span>
                                </a>
                                <a href="/logout" class="dropdown-item notify-item">
                                    <i class="mdi mdi-logout me-1"></i>
                                    <span>Cerrar sesión</span>
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="leftside-menu menuitem-active">
                <a href="/" class="logo logo-light">
                    <span class="logo-lg">
                        <img src="/img/logo-lg.svg" alt="" height="22">
                    </span>
                    <span class="logo-sm">
                        <img src="/img/logo-sm.svg" alt="" height="22">
                    </span>
                </a>

                <a href="/" class="logo logo-dark">
                    <span class="logo-lg">
                        <img src="/img/logo-lg.svg" alt="" height="22">
                    </span>
                    <span class="logo-sm">
                        <img src="/img/logo-sm.svg" alt="" height="22">
                    </span>
                </a>
                
                <button type="button" class="btn button-sm-hover p-0" data-bs-toggle="tooltip" data-bs-placement="right" aria-label="Show Full Sidebar">
                    <i class="ri-checkbox-blank-circle-line align-middle"></i>
                </button>
                
                <div class="h-100 show" id="leftside-menu-container" data-simplebar>
                    
                    <?php
                    if($this->identity() == NULL){
                        $navigation = 'Guest';
                    }else{
                        $navigation = $this->identity()['rank_level'];
                    }

                    echo $this->navigation('Laminas\Navigation\\' . $navigation)->menu()->setPartial('admin/partials/navigation.phtml');
                    ?>

                    <div class="clearfix"></div>

                </div>
            </div>

            <div class="content-page">
                <div class="content">
                    <div class="container-fluid">

                        <?php 
                        function alertMessage($text, $type = 'info'){
                            return '
                            <div class="alert alert-' . $type . ' alert-dismissible bg-' . $type . ' text-white border-0 fixed fade show" role="alert">
                                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="alert" aria-label="Close"></button>
                                ' . $text . '

                            </div>
                            ';
                        }

                        $type = ['success', 'danger', 'info'];
                        foreach([$this->successMessage, $this->errorMessage, $this->infoMessage] as $key => $message){
                            if(is_array($message)){

                                foreach($message as $single_key => $single){
                                    if(!is_array($single)) echo alertMessage($single, $type[$single_key]);
                                }

                            }
                            else{
                                if($message != NULL){
                                    echo alertMessage($message, $type[$key]);
                                }
                            }
                        }

                        echo $this->flashMessenger()->render('error', ['alert', 'alert-danger bg-danger text-white border-0 fixed fade show']);

                        echo $this->flashMessenger()->render('success', ['alert', 'alert-success bg-success text-white border-0 fixed fade show']);

                        echo $this->flashMessenger()->render('info', ['alert', 'alert-info bg-info text-white border-0 fixed fade show']);
                        
                        echo $this->content;

                        ?>

                    </div>
                </div>

                <footer class="footer">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-md-6">
                                Versión <?= $this->web['config']['version'] ?> | <a href="/admin/dashboard/logs">Ver últimos cambios</a>
                            </div>
                            <div class="col-md-6 d-none">
                                <div class="text-md-end footer-links d-none d-md-block">
                                    <a href="javascript: void(0);">Instructivo</a>
                                    <a href="javascript: void(0);">Soporte</a>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                </footer>
            </div>

        </div>
    </body>

    <script type="text/javascript" src="/js/vendor.min.js"></script>
    <script type="text/javascript" src="/js/app.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/moment.min.js"></script>
    <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.4/locale/es-us.min.js"></script>
    <script type="text/javascript" src="/js/script.js"></script>

    <?= $this->inlineScript(); ?>

</html>