<?= $this->doctype() ?>

<html lang="es" data-theme="light" data-layout-mode="fluid" data-topbar-color="light" data-sidenav-size="default" data-sidenav-color="dark" data-layout-position="fixed">

    <head>
        <meta charset="utf-8" />
        <?php 
        echo $this->headTitle('Error ' . $this->web['config']['name'])->setSeparator(' | ')->setAutoEscape(false);
        echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

        echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/favicon.svg'])
            ->prependStylesheet('/css/app-creative.min.css')
            ->prependStylesheet('/css/icons.min.css');

        ?>

        <script async src="https://www.googletagmanager.com/gtag/js?id=<?= $this->web['config']['analytics'] ?>"></script>
            <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag("js",new Date),gtag("config","<?= $this->web['config']['analytics'] ?>");</script>

    </head>

    <body class="authentication-bg">

        <div class="account-pages pt-2 pt-sm-5 pb-4 pb-sm-5">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="card">
                            <div class="card-body p-4">
                                <?= $this->content ?>

                                <a href="javascript:history.back()" class="btn btn-primary btn-sm">Volver atrás</a>
    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <footer class="footer footer-alt">
            Versión <?= $this->web['config']['version'] ?>
        </footer>
        
        <script src="/js/vendor.min.js"></script>
    	<script src="/js/app.js"></script>
    	<script src="/js/script.js"></script>

    </body>
</html>