<?php 
$this->headTitle($this->title);
$this->headLink()
	->prependStylesheet('/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css')
	->prependStylesheet('/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css')
?>

<div class="row">
	<div class="col-12">
		<div class="page-title-box">
			<h4 class="page-title"><?= $this->title ?></h4>
		</div>

		<div class="card">
			<div class="card-body table-responsive">
				<table id="datatable" class="table dt-responsive nowrap w-100">
					<thead>
	                	<th><small>Nombre completo</small></th>
	                  	<th><small>DNI</small></th>
	                  	<th><small>Email</small></th>
	                  	<th><small>Teléfono</small></th>
	                  	<th><small>Ciudad</small></th>
					</thead>
				</table>
			</div>
		</div>
	</div>
</div

<?php
$this->inlineScript()
	->prependFile('/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js')
	->prependFile('/vendor/datatables.net-responsive/js/dataTables.responsive.min.js')
	->prependFile('/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js')
	->prependFile('/vendor/datatables.net/js/jquery.dataTables.min.js')
	->captureStart();

echo <<<JS

$(document).ready(function () {
    "use strict";
    $("#datatable").DataTable({
    	ajax: {
			url: '/$this->route/get',
			type: 'POST',
        },
        columns: [
			{ data: 'full_name' },
			{ data: 'dni' },
			{ data: 'email' },
			{ data: 'phone_number' },
			{ data: 'location' },
        ],
        info: false,
        serverSide: true,
        ordering: true,
        searching: true,
        keys: true,
        language: { 
        	url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
        },
        drawCallback: function () {
            $(".dataTables_paginate > .pagination").addClass("mt-2");
        }
    });
    $(".dataTables_length select").addClass("form-select form-select-sm"),
    $(".dataTables_length label").addClass("form-label");
});


JS;
$this->inlineScript()->captureEnd();
?>