<?php $this->headTitle($this->title); ?>

<div class="row">
	<div class="col-12">
		<div class="page-title-box">
			<div class="page-title-right d-block">
				<a href="/<?= $this->route ?>/import" class="btn btn-dark btn-sm"><i class="mdi mdi-aws"></i> Importar</a>
			</div>

			<h4 class="page-title"><?= $this->title ?></h4>
		</div>

		<div class="card">
			<div class="card-body table-responsive">
				<table class="table">
					<thead>
	                	<th><small>Nombre completo</small></th>
	                  	<th><small>DNI</small></th>
	                  	<th><small>Email</small></th>
	                  	<th><small>Teléfono</small></th>
	                  	<th><small>Ciudad</small></th>
					</thead>
					<tbody>
						<?php foreach($this->results as $item): ?>
						<tr>
							<td><?= $item->getFullName() ?></td>
							<td><?= $item->getDni() ?></td>
							<td><?= $item->getEmail() ?></td>
							<td><?= $item->getPhoneNumber() ?></td>
							<td><?= $item->getLocation() ?></td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>

				<?= $this->paginationControl($this->results, 'Sliding', 'admin/partials/pagination', ['route' => $this->route]); ?>
			</div>
		</div>

	</div>
</div>