<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width" />
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <title>Cambio de contraseña</title>
</head>
<body>

  <!-- Logo -->
  <table style="width:100%;max-width:100%;" width="100%" cellspacing="0" cellpadding="0" border="0" align="center">
    <tbody>
      <tr>
        <td bgcolor="#F4F4F4" align="center">
          <table class="row" style="width:600px;max-width:600px;" width="600" cellspacing="0" cellpadding="0" border="0" align="center">
            <tbody>
              <tr>
                <td bgcolor="#F4F4F4" align="center">
                  <table class="row" style="width:540px;max-width:540px;" width="540" cellspacing="0" cellpadding="0" border="0" align="center">
                    <tbody>
                      <tr>
                        <td class="container-padding" align="center">
                          <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" class="row" style="width:540px;max-width:540px;">
                            <tbody>
                              <tr>
                                <td align="center">
                                  <table border="0" width="100%" cellpadding="0" cellspacing="0" align="center" style="width:100%; max-width:100%;">
                                    <tbody>
                                      <tr>
                                        <td height="10">&nbsp;</td>
                                      </tr>
                                      <tr>
                                        <td>
                                          <table border="0" width="100%" cellpadding="0" cellspacing="0" align="center">
                                            <tbody>
                                              <tr>
                                                <td width="180" align="center">
                                                  <a href="https://{{domain}}" target="_blank">
                                                    <img width="120" style="display:block;width:100%;max-width:120px;" alt="{{name}}" title="{{name}}" src="https://{{domain}}/img/logo.svg" draggable="false" />
                                                  </a>
                                                </td>
                                                <td>&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td height="10">&nbsp;</td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>

  <table style="width:100%;max-width:100%;" width="100%" cellspacing="0" cellpadding="0" border="0" align="center">
    <tbody>
      <tr>
        <td bgcolor="#F4F4F4" align="center">
          <table class="row" style="width:600px;max-width:600px;" width="600" cellspacing="0" cellpadding="0" border="0" align="center">
            <tbody>
              <tr>
                <td bgcolor="#ffffff" align="center">
                  <table class="row" style="width:540px;max-width:540px;" width="540" cellspacing="0" cellpadding="0" border="0" align="center">
                    <tbody>
                      <tr>
                        <td class="container-padding" align="center">
                          <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" class="row" style="width:540px;max-width:540px;">
                            <tbody>
                              <tr>
                                <td align="center">
                                  <table border="0" width="100%" cellpadding="0" cellspacing="0" align="center" style="width:100%; max-width:100%;">
                                    <tbody>
                                      <tr>
                                        <td height="40">&nbsp;</td>
                                      </tr>
                                      <tr>
                                        <td align="center" style="font-family:\'Josefin Sans\', Arial, Helvetica, sans-serif;font-size: 20px;color: #282828;">
                                          Hola {{firstname}} {{lastname}}! 
                                          <br><br>
                                          <small>Haga click en el siguiente botón para reestablecer su contraseña.</small>
                                          <br><br>
                                          <p>
                                            <a href="<?= $passwordResetUrl ?>">Reestablecer contraseña ahora.</a>
                                          </p>

                                          <small>Si usted no ha solicitado reestablecer su contraseña,<br>ignore este mensaje.</small>
                                          <br><br>
                                          <small>Si tiene problemas, copie este enlace en su navegador <a href="<?= $passwordResetUrl ?>"><?= $this->escapeHtml($passwordResetUrl) ?></a></small>
                                        </td>
                                      </tr>
                                      <tr>
                                        <td height="18">&nbsp;</td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>

  <!-- Footer -->
  <table style="width:100%;max-width:100%;" width="100%" cellspacing="0" cellpadding="0" border="0" align="center">
    <tbody>
      <tr>
        <td bgcolor="#F4F4F4" align="center">
          <table style="width:100%;max-width:100%;" width="100%" cellspacing="0" cellpadding="0" border="0" align="center">
            <tbody>
              <tr>
                <td bgcolor="#F4F4F4" align="center">
                  <table class="row" style="width:600px;max-width:600px;" width="600" cellspacing="0" cellpadding="0" border="0" align="center">
                    <tbody>
                      <tr>
                        <td bgcolor="#F4F4F4" align="center">
                          <table class="row" style="width:540px;max-width:540px;" width="540" cellspacing="0" cellpadding="0" border="0" align="center">
                            <tbody>
                              <tr>
                                <td class="container-padding" align="center">
                                  <table width="540" border="0" cellpadding="0" cellspacing="0" align="center" class="row" style="width:540px;max-width:540px;">
                                    <tbody>
                                      <tr>
                                        <td align="center">
                                          <table border="0" width="100%" cellpadding="0" cellspacing="0" align="center" style="width:100%; max-width:100%;">
                                            <tbody>
                                              <tr>
                                                <td height="40">&nbsp;</td>
                                              </tr>
                                              <tr>
                                                <td>
                                                  <table cellspacing="0" cellpadding="0" border="0" align="center">
                                                    <tbody>
                                                      <tr>
                                                        <td width="25">
                                                          <a href="https://facebook.com/{{ƒacebook}}" target="_blank">
                                                            <img width="25" style="display:block;width:100%;max-width:25px;" src="https://{{domaing}}/img/mail/fb.png" />
                                                          </a>
                                                        </td>
                                                        <td width="10">&nbsp;</td>
                                                        <td width="25">
                                                          <a href="https://instagram.com/{{instagram}}" target="_blank">
                                                            <img width="25" style="display:block;width:100%;max-width:25px;" src="https://{{domaing}}/img/mail/in.png" />
                                                          </a>
                                                        </td>
                                                      </tr>
                                                    </tbody>
                                                  </table>
                                                </td>
                                              </tr>
                                              <tr>
                                                <td height="20">&nbsp;</td>
                                              </tr>
                                              <tr>
                                                <td align="center">
                                                  <table cellspacing="0" cellpadding="0" border="0">
                                                    <tbody>
                                                      <tr>
                                                        <td align="center" style="font-family:'Roboto', Arial, Helvetica, sans-serif;font-size: 13px;color: #333;line-height: 20px">
                                                          {{name}} - {{slogan}}
                                                          <br>
                                                          {{attention_shedule}}
                                                          <br>
                                                          {{address}}
                                                        </td>
                                                      </tr>
                                                    </tbody>
                                                  </table>
                                                </td>
                                              </tr>
                                              <tr>
                                                <td height="40">&nbsp;</td>
                                              </tr>
                                            </tbody>
                                          </table>
                                        </td>
                                      </tr>
                                    </tbody>
                                  </table>
                                </td>
                              </tr>
                            </tbody>
                          </table>
                        </td>
                      </tr>
                    </tbody>
                  </table>
                </td>
              </tr>
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>

</body>
</html>