<?php $this->headTitle($this->title); ?>

<div class="row">
	<div class="col-md-8">
		<div class="page-title-box">
			<h4 class="page-title">Responder <?= $this->title ?> <small>(Doc: <?= $this->item->getDocumentId(); ?>)</small></h4>
		</div>

		<div class="card">
			<div class="card-body">
				<?php
				$form = $this->form;
				$form->prepare();
				$form->setAttribute('action', '/' . $this->route . '/edit/' . $item->getId());
				$form->setAttribute('method', 'post');
				echo $this->form()->openTag($form);
				?>
	    			<div class="row">
						<div class="col-md-12 mb-2">
							<?= $this->formRow($form->get('claim_id')) ?>
						</div>
						<div class="col-md-12 mb-2">
							<?= $this->formRow($form->get('title')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('affiliate_fullname')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('dni')) ?>
						</div>
						<div class="col-md-12">
							<?= $this->formRow($form->get('details')) ?>
							<hr>
						</div>
						<div class="col-md-12">
							<?= $this->formRow($form->get('details_answer')) ?>
						</div>
						<div class="col-md-12">
							<?= $this->formHidden($form->get('user_id')->setValue($this->identity()['id'])) ?>
							<?= $this->formSubmit($form->get('submit')) ?>
						</div>
					</div>

				<?= $this->form()->closeTag($form) ?>

			</div>
		</div>

	</div>
</div>