<?php
$this->headTitle($this->title);
$this->headLink()->prependStylesheet('/vendor/select2/css/select2.min.css')
?>

<div class="row">
	<div class="col-md-12">
		<div class="page-title-box">
			<h4 class="page-title">Agregar <?= $this->title ?></small></h5>
		</div>

		<div class="card">
			<div class="card-body">
				<?php
				$form = $this->form;
				$form->prepare();
				$form->setAttribute('action', '/' . $this->route . '/add');
				$form->setAttribute('method', 'post');
				echo $this->form()->openTag($form);
				?>
	    			<div class="row">
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('first_name')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('last_name')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('dni')) ?>
						</div>
						<div class="col-md-6 mb-2"></div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('specialties')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('registration')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('college')) ?>
						</div>
						<div class="col-md-6 mb-2"></div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('cuit')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('email')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('phone_number')) ?>
						</div>
						<div class="col-md-6 mb-2">
							<?= $this->formRow($form->get('is_active')) ?>
						</div>
						<div class="col-md-12">
							<?= $this->formSubmit($form->get('submit')) ?>
						</div>
					</div>

				<?= $this->form()->closeTag() ?>

			</div>
		</div>

	</div>
</div>

<?php 
$this->inlineScript()
  ->prependFile('//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/i18n/es.js')
  ->prependFile('//cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js');

$this->inlineScript()->captureStart();
  	echo <<<JS
	    $(document).ready(function(){
	  		$('.form-select').select2({
	  			placeholder: 'Seleccionar',
	        	theme: 'bootstrap-5',
	        	width: '100%',
	      	});
	  	});
	JS;
$this->inlineScript()->captureEnd();
?>