<?php $this->headTitle('Reestablecer contraseña | '); ?>
<div class="row align-items-center justify-content-center min-vh-100">
    <div class="col-md-6 col-lg-5 col-xl-4 py-6 py-md-0">
        <div>
            <div class="mb-3 text-center">
                <h6 class="h3 mb-1">Restablecer contraseña</h6>
            </div>
            <span class="clearfix"></span>
            <?= $this->form()->openTag($this->form); ?>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-at-sign">
                                    <circle cx="12" cy="12" r="4"></circle>
                                    <path d="M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-3.92 7.94"></path>
                                </svg>
                            </span>
                        </div>
                        <?= $this->formElement($this->form->get('email')); ?>

                    </div>
                </div>
                <div class="form-group">
                    <div class="input-group">
                        <?= $this->formElement($this->form->get('captcha')); ?>

                    </div>
                </div>
                <div class="mt-4">
                    <?= $this->formElement($this->form->get('csrf')) ?>

                    <?= $this->formElement($this->form->get('submit')); ?>

                </div>
            <?= $this->form()->closeTag(); ?>

        </div>
    </div>
</div>