<?php $this->headTitle('Nueva contraseña | '); ?>
<div class="row align-items-center justify-content-center min-vh-100">
    <div class="col-md-6 col-lg-5 col-xl-4 py-6 py-md-0">
        <div>
            <div class="mb-3 text-center">
                <h6 class="h3 mb-1">Nueva contraseña</h6>
            </div>
            <span class="clearfix"></span>
            <?= $this->form()->openTag($form); ?>

                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-key">
                                    <path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path>
                                </svg>
                            </span>
                        </div>
                        <?= $this->formElement($form->get('new_password')); ?>

                    </div>
                </div>
                <div class="form-group mb-0">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">
                                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-key">
                                    <path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path>
                                </svg>
                            </span>
                        </div>
                        <?= $this->formElement($form->get('confirm_new_password')); ?>

                    </div>
                </div>
                <div class="mt-4">
                    <?= $this->formElement($form->get('csrf')); ?>

                    <?= $this->formElement($form->get('submit')); ?>

                </div>
            <?= $this->form()->closeTag(); ?>

        </div>
    </div>
</div>