<?php $this->headTitle($this->title); ?>

<div class="row">
    <div class="col-md-6">
        <div class="page-title-box">
            <h4 class="page-title"><?= $this->title ?></h4>
        </div>

        <div class="card">
            <div class="card-body">
                <?php
                $form = $this->form;
                $form->prepare();

                if($this->actionForm != NULL){
                    $form->setAttribute('action', $this->actionForm);
                }else{
                    $form->setAttribute('action', '/' . $this->route . '/change-password/' . $this->item->getId());
                }

                $form->setAttribute('method', 'post');
                echo $this->form()->openTag($form);
                ?>
                    <div class="row">
                        <div class="col-md-6">
                            <?= $this->formLabel($form->get('new_password')) ?>
                            <div class="input-group input-group-merge">
                                <?= $this->formElement($form->get('new_password')) ?>
                                <div class="input-group-text" data-password="false">
                                    <span class="password-eye"></span>
                                </div>
                            </div>
                            <?= $this->formElementErrors($form->get('new_password')) ?>

                        </div>
                        <div class="col-md-6">
                            <?= $this->formLabel($form->get('confirm_new_password')) ?>
                            <div class="input-group input-group-merge">
                                <?= $this->formElement($form->get('confirm_new_password')) ?>
                                <div class="input-group-text" data-password="false">
                                    <span class="password-eye"></span>
                                </div>
                            </div>
                            <?= $this->formElementErrors($form->get('confirm_new_password')) ?>

                        </div>
                        <div class="col-md-12 my-2">
                            <?= $this->formHidden($form->get('csrf')) ?>
                            <?= $this->formSubmit($form->get('submit')) ?>
                        </div>
                    </div>

                <?= $this->form()->closeTag() ?>

            </div>
        </div>

    </div>
</div>