<?php $this->headTitle($this->title); ?>

<div class="row">
	<div class="col-12">
		<div class="page-title-box">
			<div class="page-title-right d-block">
				<a href="/<?= $this->route ?>/roles" class="btn btn-secondary btn-sm">Ver Roles</a>
				<a href="/<?= $this->route ?>/add" class="btn btn-primary btn-sm"><i class="mdi mdi-pencil"></i> Nuevo</a>
			</div>

			<h4 class="page-title"><?= $this->title ?></h4>
		</div>

		<div class="card">
			<div class="card-body table-responsive">
				<table class="table">
					<thead>
	                	<th><small>Nombre</small></th>
	                	<th><small>Email</small></th>
	                	<th><small>Rol</small></th>
	                	<th><small>Estado</small></th>
		                <th></th>
					</thead>
					<tbody>
						<?php foreach($this->results as $item): ?>
						<tr>
							<td><?= $item->getDisplayName() ?></td>
							<td><?= $item->getEmail() ?></td>
							<td><?= $item->getRoleId()->getName() ?></td>
							<td><?= $item->getStatusDetails() ?></td>

							<td width="20%" align="right">
								<a class="btn btn-secondary btn-sm" href="/<?= $this->route ?>/change-password/<?= $item->getId() ?>">
			                    	<i class="mdi mdi-lock"></i>
			                    </a>

								<a class="btn btn-primary btn-sm" href="/<?= $this->route ?>/edit/<?= $item->getId() ?>">
			                    	<i class="mdi mdi-pencil"></i>
			                    </a>

			                    <a class="btn btn-danger btn-sm" data-bs-toggle="modal" onclick="selectId(<?= $item->getId() ?>)" data-bs-target="#deleteModal">
			                    	<i class="mdi mdi-delete"></i>
			                    </a>
							</td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>

				<?= $this->paginationControl($this->results, 'Sliding', 'admin/partials/pagination', ['route' => $this->route]); ?>
			</div>
		</div>

	</div>
</div>