<div class="row">
	<div class="col-md-12 mx-auto">
		<section class="card card-cascade narrower my-3 mb-5" ng-controller="GenericController" ng-init="init('affiliates_family')">
			<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<h5 class="modal-title" id="deleteModalLabel">¿Está seguro de eliminar?</h5>
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
						</div>
						<div class="modal-body">
							Atención: Esta acción no se puede deshacer.
						</div>
						<div class="modal-footer">
					        <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Cancelar</button>
					        <a href="/admin/affiliates_family/delete/{{defaultItem}}" class="btn btn-danger btn-sm">Confirmar</a>
			      		</div>
			    	</div>
			  	</div>
			</div>

		  	<div class="row">
		    	<div class="col-md-12">
		      		<div class="card-header py-3 justify-content-between d-flex">
		        		<h5 class="mb-0 line-height-2"><?= $this->title ?></h5>
		        		<div class="w-auto">
		        			<a class="btn btn-success disabled" href="/admin/affiliates_family/download"><i class="fa fa-download"></i></a>
		            		<a class="btn btn-primary" href="/admin/affiliates_family/add"><i class="far fa-edit"></i></a>
		            	</div>
		      		</div>
		      		<div class="card-body card-body-cascade">
		        		<div class="row">
		          			<div class="col-md-12 mb-4 table-responsive" ng-cloak>
		          				<input type="text" ng-model="searchFilter" class="form-control mb-3" placeholder="Filtrar">

		            			<table class="table">
					              	<thead>
					                	<tr>
						                  	<th><small>Nombre completo</small></th>
						                  	<th><small>DNI</small></th>
						                  	<th><small>Email</small></th>
						                  	<th><small>CUIL Afiliado</small></th>
						                  	<th><small>Miembro</small></th>
						                  	<th><small>Opciones</small></th>
					                	</tr>
									</thead>
									<tbody>
						                <tr ng-repeat="item in filtered = (items | filter: searchFilter) | startFrom:(currentPage-1)*entryLimit | limitTo:entryLimit | orderBy: sorted">
						                	<td><small>{{item.firstname + ' ' + item.lastname}}</small></td>
						                	<td><small>{{item.dni}}</small></td>
						                	<td><small>{{item.email}}</small></td>
						                	<td><small>{{item.affiliate_dni}}</small></td>
						                	<td><small>{{item.type_of_family_member}}</small></td>
						                	<td>
							                    <a class="btn btn-success btn-sm disabled" href="/admin/affiliates_family/download/{{item.id}}">
							                    	<i class="fa fa-download"></i>
							                    </a>
						                		<a class="btn btn-primary btn-sm" href="/admin/affiliates_family/edit/{{item.id}}">
							                    	<i class="far fa-edit"></i>
							                    </a>

							                    <button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#deleteModal" ng-click="setDefaultItem(item.id)">
							                    	<i class="far fa-trash-alt"></i>
							                    </button>
						                	</td>
						                </tr>
					              	</tbody>
					            </table>
		            			<div class="pages">
		              				<ul uib-pagination ng-change="pageChanged()" previous-text="&laquo;" next-text="&raquo;" items-per-page="entryLimit" total-items="totalItems" max-size="noOfPages(filtered)" ng-model="currentPage"></ul>
		            			</div>
				          	</div>
				        </div>
			      	</div>
		    	</div>
		  	</div>
		</section>
	</div>
</div>