<?php $this->headTitle($this->title); ?>

<div class="row">
	<div class="col-12">
		<div class="page-title-box">
			<h4 class="page-title"><?= $this->title ?></h4>
		</div>

		<div class="card">
			<div class="card-body table-responsive">
				<table class="table">
					<thead>
	                  	<th><small>Nombre completo</small></th>
	                  	<th><small>DNI</small></th>
	                	<th><small>Afiliado</small></th>
	                  	<th><small>Email</small></th>
	                  	<th><small>Teléfono</small></th>
					</thead>
					<tbody>
						<?php foreach($this->results as $item): ?>
						<tr>
							<td><?= $item['full_name'] ?></td>
							<td><?= $item['dni'] ?></td>
							<td><?= $item['affiliate_full_name'] ?></td>
							<td><?= $item['email'] ?></td>
							<td><?= $item['phone_number'] ?></td>
						</tr>
						<?php endforeach; ?>
					</tbody>
				</table>

				<?= $this->paginationControl($this->results, 'Sliding', 'admin/partials/pagination', ['route' => $this->route]); ?>
			</div>
		</div>

	</div>
</div>
