<div class="row">
	<div class="col-lg-12 my-4">
		<div class="card mb-4">
		  	<div class="card-body py-3">
				<h5 class="text-center mb-3">Panel de Gestión y Administracion de Información - Aplicación Móvil de Obra Social </h5>
				<p>
				Por cuestiones de soporte, correcciones de la plataforma, comunicarse al email : info@oridhean.com. <br>
				Les solicitamos que en lo inherente a consultas, sean detallados de forma concisa y clara, asi poder brindarles la mejor asistencia. 
				</p>
				<p>
				La plataforma está en constante revisión y actualización. <br>
				Para una mejor experiencia de usuario (y para garantizar estar utilizando la última versión desplegada), <br>
				podrá consultar en el pie de página el N° de Versión del aplicativo.<br>
				Por ejemplo : N° de Versión 3.0.1.0302, los últimos 4 dígitos representan día y mes (0302) en este caso.
				</p>
				<p>
					Items genericos del Tablero Web:<br><br>

					&bull; COMISION DIRECTIVA<br>
					&bull; NOTICIAS<br>
					&bull; CREDENCIALES<br>
					&bull; ACTUALIZACION DE DATOS<br>
					&bull; TITULARES<br>
					&bull; FAMILIARES<br>
					&bull; HISTORIA CLINICA<br>
					&bull; GESTION DE TURNOS<br>
					&bull; PROFESIONALES<br>
					&bull; PAGOS AFIP<br>
					&bull; EMPRESAS<br>
					&bull; RECLAMOS
				</p>
		  	</div>
		</div>
	</div>
</div>