<?php 
$this->headTitle($this->title);
$this->headLink()
	->prependStylesheet('/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css')
	->prependStylesheet('/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css')
?>

<div class="row">
	<div class="col-md-8 my-4">
	    <div class="card mb-4">
			<div class="card-body py-3">
				<h1 class="h3 text-center mb-3"><?= $this->title ?></h1>
				
				<div class="table-responsive mb-2">
					<table id="datatable" class="table dt-responsive nowrap w-100">
						<thead>
							<th><small>Fecha</small></th>
							<th width="70%"><small>Mensaje</small></th>
						</thead>
					</table>
            	</div>
			</div>
		</div>
	</div>
</div>

<?php
$this->inlineScript()
	->prependFile('/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js')
	->prependFile('/vendor/datatables.net-responsive/js/dataTables.responsive.min.js')
	->prependFile('/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js')
	->prependFile('/vendor/datatables.net/js/jquery.dataTables.min.js')
	->captureStart();

echo <<<JS

$(document).ready(function () {
    "use strict";
    $("#datatable").DataTable({
    	ajax: {
			url: '/admin/dashboard/getNotifications',
			type: 'POST',
        },
        columns: [
			{ data: 'date',
				render: function(data, type, row, meta){
					return moment(data.date).format('lll');
				}
			},
			{ data: {text: 'text', url: 'url'},
				render: function(data, type, row, meta){
					return '<a href="' + data.url + '" target="_blank">' + data.text + '</a>';
				}
			},
        ],
        info: false,
        serverSide: true,
        ordering: false,
        searching: false,
        lengthChange: false,
        keys: false,
        language: { 
        	url: "/js/Spanish.json"
        },
        drawCallback: function () {
            $(".dataTables_paginate > .pagination").addClass("mt-2");
        }
    });
    $(".dataTables_length select").addClass("form-select form-select-sm"),
    $(".dataTables_length label").addClass("form-label");
});


JS;
$this->inlineScript()->captureEnd();
?>